### ISSUE TITLE
Error installing on a fresh yunohost

### ISSUE THREAD

**Issue by Insoleet** [duniter/duniter_ynh#35]
I installed yunohost on a home server (not a rasp but a PC), and when I'm trying to install Duniter, it fails with the following error log : 

```
++ echo https://github.com/duniter/duniter/releases/download/v1.0.1/duniter-server-v1.0.1-linux-x64.deb
++ cut -d/ -f8
+ version=v1.0.1
+ wget -nc --quiet https://github.com/duniter/duniter/releases/download/v1.0.1/duniter-server-v1.0.1-linux-x64.deb -P /tmp
+ deb=/tmp/duniter-server-v1.0.1-linux-x64.deb
+ sudo dpkg -i /tmp/duniter-server-v1.0.1-linux-x64.deb
+ sudo rm -f /tmp/duniter-server-v1.0.1-linux-x64.deb
+ sudo sed -i 's@"host".*@"host": "g1.duniter.inso.ovh",@' /opt/duniter/sources/node_modules/duniter-ui/public/cesium/config.js
+ sudo sed -i 's@"port".*@"port": "443"@' /opt/duniter/sources/node_modules/duniter-ui/public/cesium/config.js
+ sudo duniter config --ipv4 127.0.0.1 --port 10900 --remoteh g1.duniter.inso.ovh --remotep 80 --noupnp --addep 'BMAS g1.duniter.inso.ovh 443'
Attention : 2017-03-12T19:37:39+01:00 - debug: Plugging file system...
Attention : 2017-03-12T19:37:39+01:00 - debug: Loading conf...
2017-03-12T19:37:39+01:00 - warn: No configuration loaded
Attention : 2017-03-12T19:37:39+01:00 - error:  TypeError: Cannot read property 'indexOf' of undefined
Attention :     at /opt/duniter/sources/index.js:362:25
Attention :     at next (native)
Attention :     at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
Attention :     at /opt/duniter/sources/node_modules/co/index.js:54:5
Attention :     at co (/opt/duniter/sources/node_modules/co/index.js:50:10)
Attention :     at configure (/opt/duniter/sources/index.js:356:10)
Attention :     at /opt/duniter/sources/index.js:214:13
Attention :     at next (native)
Attention :     at onFulfilled (/opt/duniter/sources/node_modules/co/index.js:65:19)
Exécution du script « /var/cache/yunohost/from_file/duniter_ynh-master/scripts/remove »...

```

**Comment by M5oul** [comment]
https://paste.yunohost.org/igategisiz.rb

**Comment by M5oul** [comment]
Fixed with https://github.com/duniter/duniter_ynh/commit/f754400f3a5050bd70a92e9ed3e873e19818f1fb.
